apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marketpulse
  namespace: marketpulse
  labels:
    app.kubernetes.io/name: marketpulse
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: marketpulse.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  name: http

